# vsim -modelsimini C:/Users/mgann/Xilinix_Projects/svpwm_PL/vunit_tests/vunit_out/modelsim/modelsim.ini -wlf C:/Users/mgann/Xilinix_Projects/svpwm_PL/vunit_tests/vunit_out/test_output/testbench_lib.firing_time_generator_vunit_tb.m485a680fd78c3fed038b7ffde800b3d0bc6c860e/modelsim/vsim.wlf -quiet -t ps -onfinish stop testbench_lib.firing_time_generator_vunit_tb(tb) -L vunit_lib -L design_lib -L testbench_lib -g/firing_time_generator_vunit_tb/runner_cfg="active python runner : true,enabled_test_cases : many_calculation_check,output path : C::/Users/mgann/Xilinix_Projects/svpwm_PL/vunit_tests/vunit_out/test_output/testbench_lib.firing_time_generator_vunit_tb.m485a680fd78c3fed038b7ffde800b3d0bc6c860e/,tb path : C::/Users/mgann/Xilinix_Projects/svpwm_PL/vunit_tests/test_benches/,use_color : true" 
# Start time: 18:58:48 on Feb 06,2022
# ** Warning: (vsim-1425) C:/Users/mgann/Xilinix_Projects/svpwm_PL/vunit_tests/vunit_out/preprocessed/testbench_lib/firing_time_generator_vunit_tb.vhd(108): Absolute pathname for a VHDL external name does not start
# with an entity name that is a design root. Instead, an object with the name 'firing_time_generator_tb_inst'
# was found in the scope of design root 'firing_time_generator_vunit_tb'. This object was used as the starting
# point of the external name.
#    Time: 0 ps  Iteration: 0  Instance: /firing_time_generator_vunit_tb File: C:/Users/mgann/Xilinix_Projects/svpwm_PL/vunit_tests/vunit_out/preprocessed/testbench_lib/firing_time_generator_vunit_tb.vhd
# ** Warning: (vsim-1425) C:/Users/mgann/Xilinix_Projects/svpwm_PL/vunit_tests/vunit_out/preprocessed/testbench_lib/firing_time_generator_vunit_tb.vhd(111): Absolute pathname for a VHDL external name does not start
# with an entity name that is a design root. Instead, an object with the name 'firing_time_generator_tb_inst'
# was found in the scope of design root 'firing_time_generator_vunit_tb'. This object was used as the starting
# point of the external name.
#    Time: 0 ps  Iteration: 0  Instance: /firing_time_generator_vunit_tb File: C:/Users/mgann/Xilinix_Projects/svpwm_PL/vunit_tests/vunit_out/preprocessed/testbench_lib/firing_time_generator_vunit_tb.vhd
# ** Warning: (vsim-1425) C:/Users/mgann/Xilinix_Projects/svpwm_PL/vunit_tests/vunit_out/preprocessed/testbench_lib/firing_time_generator_vunit_tb.vhd(108): Absolute pathname for a VHDL external name does not start
# with an entity name that is a design root. Instead, an object with the name 'firing_time_generator_tb_inst'
# was found in the scope of design root 'firing_time_generator_vunit_tb'. This object was used as the starting
# point of the external name.
#    Time: 0 ps  Iteration: 0  Instance: /firing_time_generator_vunit_tb File: C:/Users/mgann/Xilinix_Projects/svpwm_PL/vunit_tests/vunit_out/preprocessed/testbench_lib/firing_time_generator_vunit_tb.vhd
# ** Warning: (vsim-8523) Cannot reference the signal "/firing_time_generator_vunit_tb/firing_time_generator_tb_inst/sim_Sector" before it has been elaborated.
#    Time: 0 ps  Iteration: 0  Instance: /firing_time_generator_vunit_tb File: C:/Users/mgann/Xilinix_Projects/svpwm_PL/vunit_tests/vunit_out/preprocessed/testbench_lib/firing_time_generator_vunit_tb.vhd
# ** Warning: (vsim-1425) C:/Users/mgann/Xilinix_Projects/svpwm_PL/vunit_tests/vunit_out/preprocessed/testbench_lib/firing_time_generator_vunit_tb.vhd(111): Absolute pathname for a VHDL external name does not start
# with an entity name that is a design root. Instead, an object with the name 'firing_time_generator_tb_inst'
# was found in the scope of design root 'firing_time_generator_vunit_tb'. This object was used as the starting
# point of the external name.
#    Time: 0 ps  Iteration: 0  Instance: /firing_time_generator_vunit_tb File: C:/Users/mgann/Xilinix_Projects/svpwm_PL/vunit_tests/vunit_out/preprocessed/testbench_lib/firing_time_generator_vunit_tb.vhd
# ** Warning: (vsim-8523) Cannot reference the signal "/firing_time_generator_vunit_tb/firing_time_generator_tb_inst/state" before it has been elaborated.
#    Time: 0 ps  Iteration: 0  Instance: /firing_time_generator_vunit_tb File: C:/Users/mgann/Xilinix_Projects/svpwm_PL/vunit_tests/vunit_out/preprocessed/testbench_lib/firing_time_generator_vunit_tb.vhd
# ** Warning: Design size of 22044 statements exceeds ModelSim-Intel FPGA Starter Edition recommended capacity.
# Expect performance to be adversely affected.
#             [22;96;49m0 ps[0m - [1;37;49mdefault[0m              -    [1;37;49mINFO[0m - -------------------------------------------------------------------------------- (firing_time_generator_vunit_tb.vhd:250)
#             [22;96;49m0 ps[0m - [1;37;49mdefault[0m              -    [1;37;49mINFO[0m - TEST CASE: many_calculation_check (firing_time_generator_vunit_tb.vhd:251)
#             [22;96;49m0 ps[0m - [1;37;49mdefault[0m              -    [1;37;49mINFO[0m - -------------------------------------------------------------------------------- (firing_time_generator_vunit_tb.vhd:252)
#        [22;96;49m230000 ps[0m - [1;37;49mcheck[0m                -   [1;31;49mERROR[0m - Check if 1 equals 0 (firing_time_generator_vunit_tb.vhd:279)
# ** Failure: Stop simulation on log level error
#    Time: 230 ns  Iteration: 0  Process: /firing_time_generator_vunit_tb/test_runner File: C:/Python310/Lib/site-packages/vunit_hdl-4.6.1rc0-py3.10.egg/vunit/vhdl/core/src/core_pkg.vhd
# Break in Subprogram core_failure at C:/Python310/Lib/site-packages/vunit_hdl-4.6.1rc0-py3.10.egg/vunit/vhdl/core/src/core_pkg.vhd line 84
# Stopped at C:/Python310/Lib/site-packages/vunit_hdl-4.6.1rc0-py3.10.egg/vunit/vhdl/core/src/core_pkg.vhd line 84
# 
# Test Run Failed!
# 
# Stack trace result from 'tb' command
#  C:/Python310/Lib/site-packages/vunit_hdl-4.6.1rc0-py3.10.egg/vunit/vhdl/core/src/core_pkg.vhd 84 return [address 0xff2b6b6a] Subprogram core_failure
# called from  C:/Python310/Lib/site-packages/vunit_hdl-4.6.1rc0-py3.10.egg/vunit/vhdl/logging/src/logger_pkg-body.vhd 749 return [address 0xff2c6f0e] Subprogram decrease_stop_count
# called from  C:/Python310/Lib/site-packages/vunit_hdl-4.6.1rc0-py3.10.egg/vunit/vhdl/logging/src/logger_pkg-body.vhd 744 return [address 0xff2c6ff6] Subprogram decrease_stop_count
# called from  C:/Python310/Lib/site-packages/vunit_hdl-4.6.1rc0-py3.10.egg/vunit/vhdl/logging/src/logger_pkg-body.vhd 923 return [address 0xff2c169d] Subprogram log
# called from  C:/Python310/Lib/site-packages/vunit_hdl-4.6.1rc0-py3.10.egg/vunit/vhdl/check/src/checker_pkg-body.vhd 121 return [address 0xff2d499c] Subprogram failing_check
# called from  C:/Python310/Lib/site-packages/vunit_hdl-4.6.1rc0-py3.10.egg/vunit/vhdl/check/src/check.vhd 196 return [address 0xff2d6493] Subprogram check
# called from  C:/Python310/Lib/site-packages/vunit_hdl-4.6.1rc0-py3.10.egg/vunit/vhdl/check/src/check.vhd 226 return [address 0xff2d66a3] Subprogram check
# called from  C:/Users/mgann/Xilinix_Projects/svpwm_PL/vunit_tests/vunit_out/preprocessed/testbench_lib/firing_time_generator_vunit_tb.vhd 279 return [address 0xff623b48] Process test_runner
# 
# 
# Surrounding code from 'see' command
#   79 :   begin
#   80 :     if core_failure_is_mocked then
#   81 :       set(core_failure_mock_state, core_failure_called_idx, 1);
#   82 :       reallocate(to_string_ptr(get(core_failure_mock_state, core_failure_message_idx)), msg);
#   83 :     else
# ->84 :       report msg severity failure;
#   85 :     end if;
#   86 :   end;
#   87 : 
#   88 :   procedure check_core_failure(msg : string := "") is
# 
